export const ACTION_FETCH_TODO_LIST = 'todoList.ACTION_FETCH_TODO_LIST';
export const ACTION_REQUEST_ADD_TODO = 'todoList.ACTION_REQUEST_ADD_TODO';
export const ACTION_REQUEST_UPDATE_TODO = 'todoList.ACTION_REQUEST_UPDATE_TODO';
